### ISSUE TITLE
python3 shebang--does this work in FreeBSD?

### ISSUE THREAD

**Issue by jimsalterjrs** [jimsalterjrs/ioztat#18]
@Freaky, I discovered after merging your patches today that ioztat does not work on the Python2.7 that my Ubuntu workstation at the home office provides with "env python". I had to update the shebang to "env python3" to get it to work again.

This should be fine for Ubuntu, but does it work in FreeBSD-land as well? I don't know if there's a `python3` executable in your environment, or whether there is only `python` and you get what you get.

**Comment by stuartthebruce** [comment]
+1 as there is no /usr/bin/python by default on RHEL 8 (or derived) systems, and for my first testing of `ioztat` I had to manually edit the shebang to `python3` for my Rocky Linux 8 systems.

**Comment by Freaky** [comment]
Yes, python is just a symlink to python3.  I should have made it that in the first place but I wasn't 100% on how universal that was.

**Comment by jimsalterjrs** [comment]
Fantastic. Thanks for the confirmation!
