### ISSUE TITLE
Output is insensitive to terminal width

### ISSUE THREAD

**Issue by Freaky** [jimsalterjrs/ioztat#23]
The current output width is 106 columns, which by happy coincidence is precisely the width of my usual terminals.

This coincidence seems unlikely to be universal, and some sensitivity to this would seem to be in order.

**Comment by jimsalterjrs** [comment]
should be fixed in #22

**Comment by Freaky** [comment]
Fixing overwrite mode fixes height, not width ;)

**Comment by jimsalterjrs** [comment]
well fooey then. reopening
