### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by Freaky** [jimsalterjrs/ioztat#35]
I think we're more or less ready to go for the next release.

Only thing that needs doing is bumping `PROGRAM_VERSION` to 2.0.0, updating `CHANGELOG.md` to add the date of release, tagging the commit, and then bumping to 2.0.1-dev.

@jimsalterjrs This has your name on it, so I don't want to just do it myself out of the blue. Everything look good, and do you want to cut the release or shall I?

**Comment by jimsalterjrs** [comment]
Hey Tom, sorry I missed this! Been crazy busy for the last couple of weeks. Thanks for your work!
