### ISSUE TITLE
No warning if zfs version too low (was: doesn't find datasets on Debian Buster, zfs 0.7.12-2)

### ISSUE THREAD

**Issue by AEI-SXSmirror** [jimsalterjrs/ioztat#38]
`ioztat -Hey` as suggested by the man page doesn't return anything.

`ioztat -SIn rpool`, also suggested by the man page, gives "dataset not found: 'rpool'" (`rpool` of course exists).

Is there a way to further debug this? Am I missing a dependency?

**Comment by Freaky** [comment]
As mentioned in the README, the minimum supported version of OpenZFS on Linux is 0.8.  Earlier versions don't export per-dataset statistics.

Might be nice to have a version check for the failure case to give a more useful error message.

**Comment by AEI-SteffenG** [comment]
Thanks, I indeed overlooked the minimum version :(

I'll modify the subject

**Comment by Freaky** [comment]
Fixed in c632a03bf329a88733abac027d1b8d0f5ad7083e for both FreeBSD and Linux, will be part of 2.0.2.

Thanks for your report - I should have done this sooner.
