### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by 0x0a11c0de** [jimsalterjrs/ioztat#4]
https://github.com/jimsalterjrs/ioztat/blob/0f8da5ff99e41460ade5bb9a8df2fe53b0eadd47/ioztat#L116

Shouldn’t this be assigning `datasets[key].name`?

**Comment by Freaky** [comment]
Yes, good catch.  Luckily this is a dead store - nothing happens to read it afterwards.

**Comment by adriaandegroot** [comment]
Perhaps L117 could be `diff.append(DatasetDiff(Dataset(), datasets[key]))` instead? The whole purpose of `d` there is to be an empty dataset, for comparison purposes, so why does it need a name at all?

(That said, I don't have enough of a handle on corner-cases of Python semantics to know how temporiaries behave in a calling context)

**Comment by Freaky** [comment]
Or just make one at the top of the function and share it across all calls.

**Comment by Freaky** [comment]
For consideration:

```python
def calcDiff(prevdatasets, datasets):
    return [DatasetDiff(prevdatasets[key], datasets[key]) for key in datasets.keys() & prevdatasets.keys()]

def calcDiffFromStart(datasets):
    zero = Dataset()
    return [DatasetDiff(zero, dataset) for dataset in datasets.values()]
```
